# Generated by Django 5.0.6 on 2025-11-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
            ],
            options={
                'verbose_name': 'Dueño',
                'verbose_name_plural': 'Dueños',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('TECH', 'Técnico'), ('CLIENT', 'Cliente'), ('OWNER', 'Dueño')], default='CLIENT', max_length=20),
        ),
    ]
