# Generated by Django 5.0.6 on 2025-11-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_create_default_estados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='titulo',
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_estimada',
            field=models.DateField(blank=True, help_text='Fecha estimada ingresada por quien crea el ticket.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='repuestos',
            field=models.TextField(blank=True, help_text='Repuestos utilizados o requeridos (opcional).', null=True),
        ),
    ]
