# Generated by Django 5.0.6 on 2025-11-23 05:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_fix_estados_6_states'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del repuesto o pieza', max_length=200)),
                ('serial', models.CharField(blank=True, help_text='Número de serie del repuesto (opcional)', max_length=100, null=True)),
                ('ean', models.CharField(blank=True, help_text='Código EAN del repuesto (opcional)', max_length=50, null=True)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se registró el repuesto')),
                ('costo', models.DecimalField(decimal_places=2, help_text='Costo del repuesto', max_digits=10)),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad de repuestos utilizados')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(blank=True, help_text='Técnico que registró el repuesto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repuestos_registrados', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(help_text='Ticket al que pertenece este repuesto', on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_registrados', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
                'ordering': ['-fecha_registro', '-creado_en'],
                'indexes': [models.Index(fields=['ticket', '-fecha_registro'], name='tickets_rep_ticket__424b70_idx')],
            },
        ),
    ]
